### ISSUE TITLE
[Feature Request]: Replace icon in systray with text GC reading.

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#10]
- Latest glucose reading in taskbar. 
- Color coded glucose numbers set to your ranges.
- Get time of reading, trend and active insulin on hover.

**Comment by Krikke99** [comment]
[Discuss]
i'm trying to get the SG in the system tray, but it looks terrible.

![image](https://user-images.githubusercontent.com/4416348/182203816-7bf4e69c-eeb5-46c4-b2f6-76d67a1cd27e.png)

i can't find a suitable font and can only use 16x16 pixels icon.

`Public Sub CreateTextIcon(str As String)
        Dim fontToUse As Font = New Font("Trebuchet MS", 10, FontStyle.Regular, GraphicsUnit.Pixel)
        Dim color As Color = Color.White
        Dim bgColor As Color = Color.Transparent
        Dim brushToUse As Brush = New SolidBrush(color)
        Dim bitmapText As Bitmap = New Bitmap(16, 16)
        Dim g As Graphics = System.Drawing.Graphics.FromImage(bitmapText)
        g.Clear(bgColor)
        g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.SingleBitPerPixelGridFit
        g.DrawString(str, fontToUse, brushToUse, -2, 0)
        Dim hIcon As IntPtr = (bitmapText.GetHicon())
        Me.NotifyIcon1.Icon = System.Drawing.Icon.FromHandle(hIcon)
    End Sub`

**Comment by paul1956** [comment]
@Krikke99  Looks great, I merged.
