### ISSUE TITLE
Datetime notation incorrect

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#12]
Datetime notation in the main screen is incorrect:

![image](https://user-images.githubusercontent.com/4416348/182604611-7547f5f4-32c7-4d86-96ae-580643cb2e34.png)

**Comment by paul1956** [comment]
@Krikke99 this is actually a string that shows exactly what the pump has internally. I am working on an update this week that will also show the time in your time zone. The JSON Lib I was using was converting date strings to local time before I ever saw them.  I don't have the raw pump data that I display and I am working to displaying it in your computers native time format and time zone. so you could look at someone's data and it would make sense I am not there yet. If you can tell me what you would like to see there please open another issue or comment on this one.

**Comment by Krikke99** [comment]
@paul1956 i just looked at a json file i get from a python program, the timezone is correct. Only the notation is not.
"lastSensorTSAsString": "2022-08-03T14:51:00.000Z"
I don't know how the notation is in other regions, in Belgium it looks like this: 03-08-2022 14:51

These are my windows settings:

![image](https://user-images.githubusercontent.com/4416348/182616112-223c2b4f-e5dd-4531-b8ec-d2784d9562f4.png)

**Comment by paul1956** [comment]
That is a string directly from pump. It's not a Date but am thinking it's confusing and will eventually convert all the dates to local culture.

**Comment by paul1956** [comment]
@Krikke99 
Fixed in [CareLinkv3.5.0.0x64](https://github.com/paul1956/CareLink/releases/tag/3.5.0.0)

Please open new issue if the issue persists
