### ISSUE TITLE
Battery status not shown

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#13]
Battery status not shown in the main screen:

![image](https://user-images.githubusercontent.com/4416348/182604970-c402f80b-1794-43ef-ae1e-ac257ff2ef52.png)

**Comment by paul1956** [comment]
@Krikke99  this is fixed in this beta
[CareLinkv3.4.3.0x64.zip](https://github.com/paul1956/CareLink/files/9251381/CareLinkv3.4.3.0x64.zip)

Reopen if you are still having issues,
