### ISSUE TITLE
crashes on every attempt

### ISSUE THREAD

**Issue by Fishbaits** [paul1956/CareLink#15]
Hi Paul

Again, thank you for all your effort.
Sorry, I am not a programmer and cannot help you much.
At moment the latest version crashes on every attempt.
It does the login but probably graph drawing causes the crash.
And yes, we have comma as decimal separator, not dot. So a number looks like 5,43
![image](https://user-images.githubusercontent.com/37698892/184610356-3dbf55ee-afc0-4747-a677-a38e3f73f55b.png)
[CareLinkErrorReport.zip](https://github.com/paul1956/CareLink/files/9336277/CareLinkErrorReport.zip)

**Comment by paul1956** [comment]
@Fishbaits This is the text file you sent running on my system and everything looks perfect with commas where they belong and 24-hour time format
![image](https://user-images.githubusercontent.com/12789369/184781779-59c1211e-c873-484b-b785-c6ecb4f26024.png)
There is an update here to prevent the overflow, if it doesn't work, I have one more thing to try then without running a debugger on your system when it crashes, I have no way to fix further.

**Comment by Fishbaits** [comment]
Still crashes.
Exception: Input string was not in a correct format.
![image](https://user-images.githubusercontent.com/37698892/184897144-c8146edf-78d9-4c81-a03c-9be2fcd93a46.png)
[CareLinkErrorReport(en-US)3.txt](https://github.com/paul1956/CareLink/files/9351637/CareLinkErrorReport.en-US.3.txt)

**Comment by Fishbaits** [comment]
![image](https://user-images.githubusercontent.com/37698892/184897505-4f9d12d9-b301-459b-8081-c19909aca15f.png)

**Comment by paul1956** [comment]
It's interesting that the error report is en-US but all the data is et-EE your local format.

**Comment by paul1956** [comment]
@Fishbaits  This version has a speciic fix for the above error even though it should not happen

**Comment by Fishbaits** [comment]
Still throws exception...
![image](https://user-images.githubusercontent.com/37698892/185083990-74b3ad8d-a0f8-4660-b9b4-c475a6ed0251.png)
[CareLinkErrorReport(en-US)5.txt](https://github.com/paul1956/CareLink/files/9358259/CareLinkErrorReport.en-US.5.txt)

**Comment by paul1956** [comment]
What language is you Windows running in and your pump? Would you like to try a remote debug session at a time that works for you. We would install a free copy of Visual Studio and connect with Chrome remote desktop.

**Comment by paul1956** [comment]
@Fishbaits your last report actually shows a different error, and I found a few more places I was parsing wrong. Please try this one.
[CareLink3.5.1.9x64.zip](https://github.com/paul1956/CareLink/files/9386546/CareLink3.5.1.9x64.zip)
.

**Comment by Fishbaits** [comment]
paul1956, there is a clear change in error messages now but it still crashed.
![image](https://user-images.githubusercontent.com/37698892/185739129-b21bfccb-49a3-4f07-bfed-36bcfdbfb5e6.png)
[CL.zip](https://github.com/paul1956/CareLink/files/9386620/CL.zip)
I am running Windows in Estonian language but I also tried it on a pc with Win10 64bit Pro Eng and got the same result.

**Comment by paul1956** [comment]
@Fishbaits thanks for you supper getting this fixed. This version has some more error reporting and some fixes. Please try.
[CareLink3.5.1.10x64.zip](https://github.com/paul1956/CareLink/files/9388211/CareLink3.5.1.10x64.zip)

**Comment by Fishbaits** [comment]
There is some visible progress - something appeared where the graph is supposed to be but still an exception is thrown.
![image](https://user-images.githubusercontent.com/37698892/185807305-fa4810ba-53ad-44b7-8927-56ad9316d120.png)
![image](https://user-images.githubusercontent.com/37698892/185807322-f45531b5-3a53-4cf5-bbf7-4ca6e13a05fb.png)
[CareLinkErrorReport(en-US)7.txt](https://github.com/paul1956/CareLink/files/9389806/CareLinkErrorReport.en-US.7.txt)

**Comment by paul1956** [comment]
@Fishbaits This will probably still crash but should produce a better report.
[CareLink3.5.1.12x64.zip](https://github.com/paul1956/CareLink/files/9391841/CareLink3.5.1.12x64.zip)
t

**Comment by Fishbaits** [comment]
Yes, it crashed.
![image](https://user-images.githubusercontent.com/37698892/185886256-3835d3de-2cef-4eb7-828e-e34de3a05131.png)
[CL.zip](https://github.com/paul1956/CareLink/files/9392982/CL.zip)

**Comment by paul1956** [comment]
Thanks for all the help. That helped a lot, I never would have found the issue. It may not be the only one. Please try this.
[CareLink3.5.1.12x64a.zip](https://github.com/paul1956/CareLink/files/9393518/CareLink3.5.1.12x64a.zip)
.

**Comment by Fishbaits** [comment]
And we have a winner!
It seems to work all properly now, no exceptions or anything.
Graph is displayed, all seems ok. Great work!!
![image](https://user-images.githubusercontent.com/37698892/185906759-75b6c52e-cf60-47fc-a305-60f83a91b2b2.png)

**Comment by paul1956** [comment]
Thanks for all your help.

**Comment by paul1956** [comment]
I am going to close
