### ISSUE TITLE
SG Trend not correct in systray

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#16]
SG Trend in systray give +0 after 1 min. update.

![image](https://user-images.githubusercontent.com/4416348/186391584-3fda02b0-7bf3-4fc0-b94c-8ec1ab98179c.png)

**Comment by paul1956** [comment]
@Krikke99 It looks like it updates it when it changes then the next 4 times the change is 0 so it displays that.
It is fixed in version 3.5.2.5.  Close if you agree.

**Comment by paul1956** [comment]
[CareLink3.5.2.5x64.zip](https://github.com/paul1956/CareLink/files/9422622/CareLink3.5.2.5x64.zip)

**Comment by Krikke99** [comment]
Issue is fixed.
