### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#17]
Login failed if the application is minimized for a while.

![image](https://user-images.githubusercontent.com/4416348/186405759-4f12a03c-fe30-4f8b-88bf-f017a8132c58.png)

**Comment by paul1956** [comment]
@Krikke99 CareLink has been very flakey especially in Europe due to DNS issues. If I fail twice, I just give up. I will look into retrying. CareLink has a 3 try and then you get kicked out for 15 minutes and I don't want to hit that. Open to any suggestions.

**Comment by paul1956** [comment]
@Krikke99  I think this is fixed in 3.5.3.0 which I am posting now.

**Comment by Krikke99** [comment]
@paul1956 the problem remains in version 3.5.3.0

**Comment by paul1956** [comment]
@Krikke99 I found something in the retry logic that may cause it. I will post a fix Sunday.

**Comment by paul1956** [comment]
@Krikke99 Fixed in latest release. Please close if you agree.

**Comment by Krikke99** [comment]
@paul1956 now the application does not update anymore.
After 1 minute:
![image](https://user-images.githubusercontent.com/4416348/188870931-81cd2b60-5229-4a44-a385-8a0042eb68e3.png)
After 5 minutes:
![image](https://user-images.githubusercontent.com/4416348/188871379-96297909-151d-42d7-b970-989ca97a204c.png)

**Comment by paul1956** [comment]
I have rewritten the login logic in CareLink3.5.5.0x64 Let me know if it fixes the problem

**Comment by Krikke99** [comment]
@paul1956 
In in CareLink3.5.5.0x64 no error message anymore , but also no updates.

![image](https://user-images.githubusercontent.com/4416348/189074549-cc7c0d46-17c7-449c-bef5-22338c5af7bd.png)
![image](https://user-images.githubusercontent.com/4416348/189074611-97de54c9-4eb8-4c28-85ef-714f70fb2239.png)

**Comment by paul1956** [comment]
@Krikke99 Think I finally found it, server is asked for reauthorization, and I was ignoring it.

**Comment by paul1956** [comment]
@Krikke99 I have put in 2 for fixed for this issue in CareLink3.5.5.1x64 hopefully they work for you.

**Comment by paul1956** [comment]
@Krikke99 I look like Carelink is getting more aggressive with requiring reauthorizing. I was only doing it when the previous one expired every 24 hours. In the past retrying just worked not I need to relog in. Hopefully this works.
