### ISSUE TITLE
Timezone issue... Central European Summer Time

### ISSUE THREAD

**Issue by HJADR** [paul1956/CareLink#19]
![image](https://user-images.githubusercontent.com/4594450/189751634-4c32d49b-663e-4940-a78a-9bf130567cdd.png)

I am not sure what to select.  Selected cancel 2 times, but I see no created issue. And well... I am just not sure, might be a problem English not beeing my native language...

**Comment by paul1956** [comment]
You need to say Yes and it will stop prompting you or No and it will keep asking. In your case you can send this file CareLinkLastDownload(en-US).json  in you Documents folder. (en-US) will be something else as "en" is English and "US" is my country.

**Comment by HJADR** [comment]
[CareLinkLastDownload(nl-NL).zip](https://github.com/paul1956/CareLink/files/9558092/CareLinkLastDownload.nl-NL.zip)

Here you go

**Comment by paul1956** [comment]
Timezone issue should also be fixed in 3.5.5.3
