### ISSUE TITLE
Unhandled exception 3.5.6.6

### ISSUE THREAD

**Issue by mattimart** [paul1956/CareLink#22]
The only working release for me is 3.5.4.12

![image](https://user-images.githubusercontent.com/44461571/193218363-53565eb2-1f37-4aeb-9bb8-26060e87252e.png)

**Comment by mattimart** [comment]
I have solved deleting Carelink.csv in MyDocuments folder.

**Comment by paul1956** [comment]
@mattimart how did you solve? Do I need to make any code changes?
