### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by Krikke99** [paul1956/CareLink#24]
After the latest commit 6e8074786d1ed7cf8b5ea2470cdb70c85113adea i get this error:

![image](https://user-images.githubusercontent.com/4416348/195021940-9abadce6-d248-4868-9347-490a321e5fa4.png)
[CareLinkErrorReport(en-BE).txt](https://github.com/paul1956/CareLink/files/9752130/CareLinkErrorReport.en-BE.txt)

**Comment by paul1956** [comment]
Fixed in CareLink3.5.6.10x64 thanks it on shows up on 780G. Close if you argee.

**Comment by Krikke99** [comment]
Fixed!
