### ISSUE TITLE
Problems after first start

### ISSUE THREAD

**Issue by Bernsti76** [paul1956/CareLink#26]
![Screenshot 2022-10-21 165614](https://user-images.githubusercontent.com/116485280/197382262-1e1a192b-6783-408c-80c8-bb3deab1f150.jpg)

I get this after the first start at every next start of the programme.

**Comment by paul1956** [comment]
@Bernsti76 You can also try deleting CareLink.csv. Sometimes it gets corrupt. I found the reason and need to update my code.

**Comment by paul1956** [comment]
@Bernsti76 This should fix your issue, but it is not ready for release you may get some popup boxes. You will need to delete careLink.csv it is definitely corrupted, updated with other fixes.
[CareLink3.5.7.0x64.zip](https://github.com/paul1956/CareLink/files/9855486/CareLink3.5.7.0x64.zip)

**Comment by Bernsti76** [comment]
> @Bernsti76 You can also try deleting CareLink.csv. Sometimes it gets corrupt. I found the reason and need to update my code.

Thank you so much! After deleting CareLink.csv everything is working again!

**Comment by paul1956** [comment]
@Bernsti76 I need to figure out why is gets corrupt, I will close this.
