### ISSUE TITLE
dotNET 7.0.0

### ISSUE THREAD

**Issue by HJADR** [paul1956/CareLink#28]
Dear Paul,
I just updated your programm. Now I got a prompt telling me to install dotNET 7.
The issue is I already have that installed. So.... any clue?

![image](https://user-images.githubusercontent.com/4594450/201206682-0b30a941-2ba7-44a2-9dc7-4710c072c2d1.png)

CareLink3.5.6.7 works fine by the way. :)

**Comment by paul1956** [comment]
What if you try to download it. You can have many versions and they don't interfere with each other.

**Comment by paul1956** [comment]
Comment with instructions on adding .Net 7.0. added to ReadMe on Release page.
