### ISSUE TITLE
The program location CollectMarkers line 52 is thought to be unreachable.

### ISSUE THREAD

**Issue by JJP780G** [paul1956/CareLink#29]
[CareLinkErrorReport(en-CY)6.txt](https://github.com/paul1956/CareLink/files/9986238/CareLinkErrorReport.en-CY.6.txt)

**Comment by JJP780G** [comment]
Thank you for all the work you put into this, I find it extremely helpful seeing the basal auto mode (with stable levels) uses and then applying that to manual mode.  
Many Thanks

**Comment by paul1956** [comment]
@JJP780G Thanks, its fixed in latest release. CareLink3.5.7.7x64

Close if you agree.

**Comment by JJP780G** [comment]
This has indeed been fixed. 
Many Thanks once again for all your help.
