### ISSUE TITLE
Doesnt add up

### ISSUE THREAD

**Issue by JJP780G** [paul1956/CareLink#31]
![image](https://user-images.githubusercontent.com/91048750/203894314-2878c7b5-7e6e-4e69-8226-d59f90d7e4d4.png)

Doing the maths the total insulin should be 16.1 units not 13.9

I am using the previous version as the new version shuts down while trying to enter the username. 

Many Thanks

**Comment by paul1956** [comment]
Delete CareLink.csv that should address the shutdown issue.

 

I need the data file in My Documents to look at the Math. What pump?

 

From: JJP780G ***@***.***> 
Sent: Friday, November 25, 2022 12:27 AM
To: paul1956/CareLink ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paul1956/CareLink] Doesnt add up (Issue #31)

 

 <https://user-images.githubusercontent.com/91048750/203894314-2878c7b5-7e6e-4e69-8226-d59f90d7e4d4.png> 

Doing the maths the total insulin should be 16.1 units not 13.9

I am using the previous version as the new version shuts down while trying to enter the username.

Many Thanks

**Comment by paul1956** [comment]
@JJP780G 
Math error fixed in CareLink3.5.7.9x64

Please close of you agree or attach CareLinkLastDownload(en-US).json file. name will vary based on country. It is a text file you can review all private information should be deleted.
