### ISSUE TITLE
Carelink for Windows shuts down when trying to change user in the login field.

### ISSUE THREAD

**Issue by BenoitVDBr** [paul1956/CareLink#33]
Hello,

I downloaded the latest release to see the changes you made. When I tried to connect and was typing the login, the app freezes for a few seconds and then shuts down.

Wkr,
Benoit Van Den Broecke.

**Comment by paul1956** [comment]
@BenoitVDBr Delete Documents/Carelink.csv and if you find any other Carelink documents delete them as well. If that does not fix issue let me know.

**Comment by paul1956** [comment]
@BenoitVDBr did that fix issue, if so please close.

**Comment by BenoitVDBr** [comment]
Hello Paul,

yes, it did fix the issue. Thanks for the follow-up!

Wkr,
Benoit.
