### ISSUE TITLE
what does it mean AIT?

### ISSUE THREAD

**Issue by errezeta67** [paul1956/CareLink#35]
what does it mean AIT

**Comment by paul1956** [comment]
@errezeta67 AIT is Active Insulin Time and is only 1 of 2 things you control in AutoMode but the app calculates if differently than the pump. The pump displays AIT for your Bolus ONLY. But to control AIT you need real AIT which includes basal insulin (true AIT). 

The AIT Graph shows true AIT, and this graph should never hit 0. There are 2 algorithms used to display the data, one plots using the value you entered in your pump, the advanced algorithm more accurately reflects what your body is doing with Humalog or FIASP type insulin. I recommend Advanced but you can select and easily change.

If this answers your question, please close or ask additional questions here.
