### ISSUE TITLE
Failing install on Windows11 PC  (working on my Win 10 PC)

### ISSUE THREAD

**Issue by casellir** [paul1956/CareLink#37]
[CareLinkErrorReport(en-US)2.txt](https://github.com/paul1956/CareLink/files/10899041/CareLinkErrorReport.en-US.2.txt)

**Comment by paul1956** [comment]
@casellir, see if this fixes the issue,
[CareLink3.6.0.2x64.zip](https://github.com/paul1956/CareLink/files/10902917/CareLink3.6.0.2x64.zip)

**Comment by paul1956** [comment]
@casellir this issue is closed in CareLink3.6.0.3.

Please close if you agree

**Comment by casellir** [comment]
I'm not able to test until tomorrow, but I'm confident, thanks.
