### ISSUE TITLE
Question about database feature

### ISSUE THREAD

**Issue by tloczekt** [paul1956/CareLink#4]
At first thank you very much for your hard work.
Anyway I have a question whether do you plan to store longer history on any database (like Nightscout) for statistic's features or not ?

**Comment by paul1956** [comment]
@tloczekt No, this is live data from CareLink everything is on your local computer I don't have any database. The one place I might is in active insulin time where it am missing the first x values where x is active insulin time * x and that would just be to show the beginning of the graph. You can save snapshots of interesting data (and reload later) from the Start menu and the program keeps 1 snapshot in case of a crash.
