### ISSUE TITLE
Visual bug and "report a bug button"

### ISSUE THREAD

**Issue by nfontan** [paul1956/CareLink#40]
the new version seems to have some sort of visual bug. The basal and bolus lines were too small.
![image](https://user-images.githubusercontent.com/51861356/223517640-9432bfbf-a579-48bd-8fc3-fe5956be8351.png)

An other error when clink on "report a bug"
![image](https://user-images.githubusercontent.com/51861356/223517762-8c3dd4d8-4427-43d6-9fd6-290c287fc160.png)

my chrome is installed on C:\Program Files\Google\Chrome\Application
[CareLinkErrorReport(en-US).txt](https://github.com/paul1956/CareLink/files/10912874/CareLinkErrorReport.en-US.txt)

are you still using gitter?

Thanks

**Comment by paul1956** [comment]
Browser bug fixed in 3.6.0.4

Yes, still on Gitter using new version.

I am closing as visual bug is already reported.

**Comment by paul1956** [comment]
@nfontan This is fixed in the current version it happened when comma is used was decimal separator which I mostly handled but I missed 1. It also has the ability to export the larger tables to Clipboard for a Formatted Excel.
