### ISSUE TITLE
version 3.6.1.2 crash

### ISSUE THREAD

**Issue by alexklit** [paul1956/CareLink#41]
In the version 3.6.1.2 the app the app crash.
[CareLinkErrorReport(en-US).txt](https://github.com/paul1956/CareLink/files/11025476/CareLinkErrorReport.en-US.txt)

**Comment by paul1956** [comment]
@alexklit I don't know what to do with a date that looks like '20/3/2023 7:05:49 Ï€Î¼'

**Comment by alexklit** [comment]
The application worked properly before the version 3.6 with the same
regional settings.
Regards
Klitorakis Alexandros

Στις Τρί 21 Μαρ 2023 στις 9:43 π.μ., ο/η Paul M Cohen <
***@***.***> έγραψε:

**Comment by paul1956** [comment]
@alexklit sorry you are correct. I found the issue.
[CareLink3.6.2.0x64.zip](https://github.com/paul1956/CareLink/files/11027014/CareLink3.6.2.0x64.zip)
See if this fixes it. If not the error will be somewhere else and I will need another report.

**Comment by alexklit** [comment]
Thank you, it works properly.
Regards
Klitorakis Alexandros

Στις Τρί 21 Μαρ 2023, 12:07 ο χρήστης Paul M Cohen ***@***.***>
έγραψε:
