### ISSUE TITLE
Widget not fully showing the numbers and change to glucose levels

### ISSUE THREAD

**Issue by Ryptahi** [paul1956/CareLink#43]
<img width="133" alt="image" src="https://github.com/paul1956/CareLink/assets/41555174/fdcaaf1d-7d7a-4db2-991c-357cc6910631">

I noticed that when I have it show blood glucose in mmol/L the decimal numbers do not show correctly. Also change to the blood glucose is shown as -1 when actual change was -0.60. This issue is most likely only with european way of using mmol/L vs mg/dL, but could it be possible to show actual changes in decimals as well, as it feels like a bug or oversight.

**Comment by paul1956** [comment]
@Ryptahi Do you mean the "," because that comes from your local Windows settings. The fact that it doesn't fit is a real issue that I will look at. But I have no test sites that use mmol/L so it will be difficult to reproduce.

**Comment by paul1956** [comment]
@Ryptahi please try this
[CareLink3.8.2.0x64.zip](https://github.com/paul1956/CareLink/files/11716846/CareLink3.8.2.0x64.zip)

**Comment by Ryptahi** [comment]
> @Ryptahi please try this [CareLink3.8.2.0x64.zip](https://github.com/paul1956/CareLink/files/11716846/CareLink3.8.2.0x64.zip)

Thank you, now it is absolutely perfect!
<img width="130" alt="image" src="https://github.com/paul1956/CareLink/assets/41555174/f59bb21a-598f-4dea-8cfd-7ff6f499a52c">

**Comment by paul1956** [comment]
Thanks I will update and release a new version today.
