### ISSUE TITLE
Login fail after 2023.06.26 Medtronic site maintenance

### ISSUE THREAD

**Issue by sbecze** [paul1956/CareLink#44]
Login is not possible after 2023.06.27 Carelink site maintenance/update. Error: "Gateway Time-out."

**Comment by paul1956** [comment]
@sbecze There is a prerelease update posted yesterday 3.8.3.0 that fixes the issue.

Please close if it works or let me know if not and provide your region/county if not.

**Comment by sbecze** [comment]
I was trying the v3.8.3.0 with EU/GB region and both patient/care partner role without success. Today it started to work without any change, I assume there was a server outage. 
Thank you for the great work.
