### ISSUE TITLE
first time user. not able to login with account of Australia.

### ISSUE THREAD

**Issue by kk001kk** [paul1956/CareLink#47]

**Comment by paul1956** [comment]
@kk001kk I need more information? Is there an error? Are there any files in MyDocuments/CareLink
I am also posting a new version today that might fix your issue.

Also, can you share the CareLink server URL. I assume it is http://carelink.minimed.eu

**Comment by paul1956** [comment]
@kk001kk You can try this prerelease 
[CareLink3.9.0.1x64.zip](https://github.com/paul1956/CareLink/files/12518484/CareLink3.9.0.1x64.zip)

**Comment by paul1956** [comment]
@kk001kk any update or I will close I have just posted a newer version, if it fixes your issue please close otherwise I need more information.

**Comment by paul1956** [comment]
@kk001kk since I have no actionable information I will close. If you are still having issues please reopen.
