### ISSUE TITLE
Data unavailable Safe Meal Reduction.

### ISSUE THREAD

**Issue by IoanaSara** [paul1956/CareLink#56]
Data from the Safe Meal Reduction report is not available.

![Safe Meal Reduction](https://github.com/paul1956/CareLink/assets/113257829/4b00cae0-a931-4c1e-bbdf-0bb4f550b4e9)

**Comment by paul1956** [comment]
Save meal reduction is a calculation base on your CareLink Settings file. If it is unable to download an English settings file it will not display SafeMealReduction. You can download the file manually and then use the programs Start Here menu to import the file. It expects the file in your download directory. Safe meal reduction is a calculation based on the size of your bolus based on pump settings and what is delivered.

 

If you are seeing something different let me know.

 

 

 

 

From: IoanaSara ***@***.***> 
Sent: Sunday, March 10, 2024 12:25 AM
To: paul1956/CareLink ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paul1956/CareLink] Data unavailable Safe Meal Reduction. (Issue #56)

 

Data from the Safe Meal Reduction report is not available.

Safe.Meal.Reduction.png (view on web) <https://github.com/paul1956/CareLink/assets/113257829/4b00cae0-a931-4c1e-bbdf-0bb4f550b4e9>

**Comment by paul1956** [comment]
Fixed
