### ISSUE TITLE
Data difference at expoort in excel file

### ISSUE THREAD

**Issue by IoanaSara** [paul1956/CareLink#57]
When exporting the data from Auto Basal Delivery Markers, I noticed that the Basal Rate values ​​in the excel file are not identical to those in Carelink.
![AutoBasalExcel](https://github.com/paul1956/CareLink/assets/113257829/ee663fc1-8d21-4cde-b1b3-805feefba537)

**Comment by paul1956** [comment]
Can you post a saved snapshot file that I can export to excel to see difference? Snapshots have all personal information removed. Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Mar 10, 2024, at 12:37 AM, IoanaSara ***@***.***> wrote:﻿
When exporting the data from Auto Basal Delivery Markers, I noticed that the Basal Rate values ​​in the excel file are not identical to those in Carelink.
AutoBasalExcel.png (view on web)

**Comment by IoanaSara** [comment]
Hello,I hope the attached files are good.I notice that the differences are 
Thank you very much!


    Pe luni, 11 martie 2024 la 03:16:41 EET, Paul M Cohen ***@***.***> a scris:  
 
 

Can you post a saved snapshot file that I can export to excel to see difference? Snapshots have all personal information removed. Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Mar 10, 2024, at 12:37 AM, IoanaSara ***@***.***> wrote:﻿
When exporting the data from Auto Basal Delivery Markers, I noticed that the Basal Rate values ​​in the excel file are not identical to those in Carelink.
AutoBasalExcel.png (view on web)

**Comment by paul1956** [comment]
@IoanaSara
Great catch the faction that was rounding Basal values was very messed up with certain values and .075 was rounding to .050 is just one example.
Version CareLink4.0.0.15x64 fixes it and should also fix Meal Reduction

Fix so please close one of both issues.

**Comment by IoanaSara** [comment]
Hello,Version 4.0.0.16 solved the rounding problem, there are no more differences.Safe Meal Reduction data are not yet available.To view the Safe Meal Reduction, it is necessary to access: Start Here -> Use Test Data; Start Here -> Use Last Data File.Thank you very much!

    Pe luni, 11 martie 2024 la 11:10:47 EET, Paul M Cohen ***@***.***> a scris:  
 
 


@IoanaSara
Great catch the faction that was rounding Basal values was very messed up with certain values and .075 was rounding to .050 is just one example.
Version CareLink4.0.0.15x64 fixes it and should also fix Meal Reduction

Fix so please close one of both issues.

**Comment by paul1956** [comment]
Fixed
