### ISSUE TITLE
Axis Object - The minimum value of the axis is greater than the largest data point value.

### ISSUE THREAD

**Issue by BennMcKenzie** [paul1956/CareLink#61]
System Log's in then loads some text data and pump settings such as AIT , Serial Number data but fails with above exception whilst trying to load the Main view and shows a big white box with a red X through it then crashes Possibly cause by Time Changes? Discovered Pump was 12 hours ahead during weekend Am/PM was messed up fixed AM/PM issue but that forced pump 24 hours ahead so then had to fix date as well
[CareLinkErrorReport(en-NZ)4.txt](https://github.com/user-attachments/files/15949049/CareLinkErrorReport.en-NZ.4.txt)

**Comment by BennMcKenzie** [comment]
If I don't login then change to another view I can Login and go through the other views its only the Main screen

**Comment by paul1956** [comment]
@BennMcKenzie It looks like you have changed time, and day and the program does not handle that case. You can look at the SG Table and see that the time starts on 24th then goes to 23rd and then back to 24th. It will clear up in 24 hours. I will look at a fix.

**Comment by paul1956** [comment]
Version 4.0.1.4 fixes the issue. Please close if issue is fixed

**Comment by BennMcKenzie** [comment]
Hi Paul, 

You are correct with time/date changes but your latest version has 100% fixed the issue
