### ISSUE TITLE
change unit 

### ISSUE THREAD

**Issue by Fishbaits** [paul1956/CareLink#9]
Is there a way to change unit from mg/dL to mmol/L?
At my country we usually use mmol/L and numbers are (or should be at best) around 5.5.
As the values are in these ranges, it messes up the graph.
![image](https://user-images.githubusercontent.com/37698892/182187929-e3dd1b2a-ed7c-4264-bec3-54eaf2ba7d1e.png)

**Comment by paul1956** [comment]
@Fishbaits  The graph mess up is related to date issue. It should automatically pick up units data from your pump. If you can upload the CareLink*.json file from your documents folder I can look into it further.

The json file is readable text and personal data is removed if you save as snapshot from the Start Up Menu of the app.

**Comment by paul1956** [comment]
@Fishbaits 
Good catch on the unknown, this was a bug I introduced this week, while fixing a different issue. Nothing to do with units.


![image](https://user-images.githubusercontent.com/12789369/182607362-ce4f260c-d2e6-488e-82d9-4c4652a66670.png)

This version should have both issues fixed and also a new tray icon with critical data
[CareLinkv3.4.3.0x64.zip](https://github.com/paul1956/CareLink/files/9251274/CareLinkv3.4.3.0x64.zip)

This is still a beta version

**Comment by Fishbaits** [comment]
When I try to run this new version, it says so:
![image](https://user-images.githubusercontent.com/37698892/182690675-abeec65f-47a0-4232-9269-f3f42967fae3.png)
And then quits, no matter if I click OK or Cancel

**Comment by paul1956** [comment]
@Fishbaits thanks. I will upload a trial fix tomorrow.

This information will help.

**Comment by paul1956** [comment]
@Fishbaits It looks like the pump stores and reports everything in mg/dl and display software scales it. So all the data is there but off the top of the graph. It is going to take some time to scale everything. I was going to post something that works today but it would be in US units. I will work on fixing the units next week.

**Comment by paul1956** [comment]
@Fishbaits 
Fixed in [CareLinkv3.5.0.0x64](https://github.com/paul1956/CareLink/releases/tag/3.5.0.0)

Please open new issue if the issue persists
